apiVersion: v1
kind: Pod
metadata:
  name: jenkins-airflow-helm
spec:
  containers:
  - name: gcloud-helm
    image: quay.io/logistio/gcloud-helm:latest
    imagePullPolicy: Always
    resources:
      requests:
        memory: 0.5Gi
        cpu: "0.1"
      limits:
        memory: 0.5Gi
        cpu: "0.5"
    command:
    - cat
    tty: true
  - name: jnlp
    image: jenkins/jnlp-slave:3.23-1
    resources:
      requests:
        memory: 0.5Gi
        cpu: "0.1"
      limits:
        memory: 0.5Gi
        cpu: "0.5"
    imagePullPolicy: IfNotPresent
    tty: true


