webScheduler:
  tag: "0.2-oracle"
  imagePullPolicy: Always
  installWebServer: true
  installScheduler: true
  dagsVolumeClaim: airflow-dags
  web:
    authenticate: False
    authBackend: airflow.contrib.auth.backends.google_auth
    googleAuthDomain: logistio.ie
    googleAuthSecret: google-oauth
    googleAuthSecretClientIDKey: client_id
    googleAuthSecretClientSecretKey: client_secret
  preHook: 
    install: true
  scheduler:
    dagVolumeReadOnly: false
    schedulerHeartbeatSec: 1

dagVolume:
  installPV: true
  installPVC: true
  nfsServer: "12.345.6.7"
  nfsPath: /dags

createWorkerRBAC: true
installPostgresService: true
installCloudsqlProxyDeploy: true

airflowCfg:
  core:
    executor: KubernetesExecutor
  kubernetes:
    namespace: airflow
  kubernetesNodeSelectors: |-
ingress:
  enabled: true
  hosts: 
    - airflow.mysite.io
  tls:
  - hosts:
    - airflow.mysite.io
    secretName: airflow.mysite.io