{{- if and .Values.google.enabled .Values.installCloudsqlProxyDeploy -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ template "airflow.postgresql.fullname" . }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
  labels:
    app.kubernetes.io/name: {{ template "airflow.name" . }}
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "airflow.name" . }}
      app: {{ template "airflow.name" . }}
      tier: "{{ template "airflow.postgresql.fullname" . }}"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "airflow.name" . }}
        app: {{ template "airflow.name" . }}
        tier: "{{ template "airflow.postgresql.fullname" . }}"
    spec:
      restartPolicy: Always
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances={{ .Values.google.project }}:{{ .Values.google.region }}:{{ .Values.google.databaseInstance }}:{{ .Values.google.databaseName }}=tcp:0.0.0.0:5432"]
          ports:
            - name: postgres
              containerPort: 5432
    {{- with .Values.webScheduler.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end -}}