{{- if and .Values.google.enabled .Values.logVolume.installPV -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-40"
  name: {{ .Values.webScheduler.logsVolumeClaim }}
  labels:
    app.kubernetes.io/name: {{ template "airflow.name" . }}
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.logVolume.size }}
  accessModes:
  - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"
{{- end -}}
