{{- if and .Values.google.enabled .Values.dagVolume.installPVC -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-35"
  name: {{ .Values.webScheduler.dagsVolumeClaim }}
  labels:
    app.kubernetes.io/name: {{ template "airflow.name" . }}
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  # https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes
  storageClassName: ""
  accessModes:
  # accessModes do not enforce access right, but rather act as labels to match a PV to a PVC.
    - "ReadWriteMany"
  volumeName: {{ .Values.webScheduler.dagsVolumeClaim }}
  resources:
    requests:
      storage: {{ .Values.dagVolume.size }}
{{- end -}}