{{- if and .Values.azure.enabled .Values.azure.createAzureFileStorageClass -}}
# https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-40"
  name: {{ .Values.azure.azureFileStorageClassName }}
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
  location: {{ .Values.azure.location }}
  storageAccount: {{ .Values.azure.storageAccountName }}
{{- end -}}