{{- if .Values.dagVolume.installPV -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-40"
  name: {{ .Values.webScheduler.dagsVolumeClaim}}
spec:
  capacity:
    storage: {{ .Values.dagVolume.size }}
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadOnlyMany
  nfs:
    server: {{ .Values.dagVolume.nfsServer }}
    path: {{ .Values.dagVolume.nfsPath }}
{{- end -}}
