apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "airflow.name" . }}
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.webScheduler.web.service.type }}
  ports:
    - port: {{ .Values.webScheduler.web.service.port }}
      targetPort: {{ .Values.webScheduler.web.service.port }}
      protocol: TCP
      name: web
  selector:
    app: {{ template "airflow.name" . }}
    tier: {{ .Values.webScheduler.web.name }}
