{{- if and .Values.local.enabled .Values.dagVolume.installPV -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-40"
  name: {{ .Values.webScheduler.dagsVolumeClaim}}
  labels:
    app.kubernetes.io/name: {{ template "airflow.name" . }}
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.dagVolume.size }}
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadOnlyMany
  hostPath:
    path: {{ .Values.local.dagFolder }}
    type: Directory
  storageClassName: hostpath
{{- end -}}
