{{- if .Values.nfs.createServer -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-200"
  name: {{ .Values.nfs.PVCName }}
  labels:
    app.kubernetes.io/name: {{ template "airflow.name" . }}
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
  # accessModes do not enforce access right, but rather act as labels to match a PV to a PVC.
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.nfs.PVCSize }}
{{- end -}}
