{{- if .Values.nfs.createServer -}}
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-100"
  labels:
    app.kubernetes.io/name: {{ template "airflow.name" . }}
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
{{- end -}}