namespace: default

google:
  enabled: False
azure:
  enabled: False

local:
  enabled: true
  createLogPVC: true
  createDagPVC: true
  dagFolder: 
  logFolder: 

# Leave dag subpath empty as it's not an NFS subdirectory
dagVolume:
  dagSubPath: 
webScheduler: 
  web:
    name: web
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
  scheduler:
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi

airflowCfg:
  kubernetes:
    namespace: default